### ISSUE TITLE
Feature request: add nomic-embed-text-v2 or other multilingual embedding model

### ISSUE THREAD

**Issue by aginiewicz** [brianpetro/obsidian-smart-connections#1024]
Hello, first of all, great plugin. I plan to cover Smart Connections plugin in my introductory computer science book for mathematicians, but most notes of my students are not in English and I would like to describe a solution, which will have reliable embedding quality for non-english texts. Is adding nomic-embed-text-v2 planned? Having good multilingual embedding model is important feature for project of mine (especially I like nomic family of models, because they are fully open – with open data, open code and open weights). 

Is there plan to support lm_studio served embedding models? Then I could plug in any model that works best at any given time or test multiple ones without requests. I've seen similar request for ollama #559, is there some roadmap for this?

**Comment by brianpetro** [comment]
Hi @aginiewicz and thanks for your interest in Smart Connections 😊 

Yes, external local model platforms are planned and the adapter architecture that's used by the `smart-embed-model` module supports adding those platforms with relative ease. 

I don't currently have a ETA for this development. Supporting additional platforms via new adapters is something I am hoping the community will be able to contribute (I know the process isn't well documented right now, but I believe my time is best spent enabling others to build those adapters rather than doing them myself since the potential for new services that could be implemented with an adapter is near limitless).

I hope that makes sense, and thanks again for your interest in the project 🌴

**Comment by aginiewicz** [comment]
> the adapter architecture that's used by the smart-embed-model module supports adding those platforms with relative ease

Thanks for reply! Is this part already supported, i.e. a pull request to jsbrains and for example adding new model in https://github.com/brianpetro/jsbrains/blob/main/smart-embed-model/adapters/transformers.js#L197 are possible, and it has chance to be released as part of obsidian-smart-connections plugin relatively soon after pull request, or there is some architecture work that needs to be done before new models can be accepted?

**Comment by brianpetro** [comment]
@aginiewicz yes, adding a model to an existing adapter, i.e. the transformers adapter, is that easy.

Adding a completely new adapter would require a few more steps and some testing, but still relatively easy for integrating an entirely new platform/service 🌴

**Comment by aginiewicz** [comment]
Tried to look into it, but I have another question. Seems the nomic v2 can be used as a transformer just like nomic v1.5, which is already added, but both those models according to docs work best if they are prefixed with search_document: or search_query: (see for example https://huggingface.co/nomic-ai/nomic-embed-text-v2-moe#transformers and https://docs.fireworks.ai/guides/querying-embeddings-models#embedding-queries-and-document – seems search_document prefix is right for our usecase). Are different prefixes for various models somehow supported somewhere down the stack (in one of smart-embed-model dependencies)?

**Comment by brianpetro** [comment]
Hi @aginiewicz and thanks for sharing those resources.

In terms of the architecture, model-specific adaptations should be implemented as an adapter in the `smart-embed-model` module.

There is also the `smart-entities` collection which implements the `smart-embed-model` in `smart-environment`. I mention this because configuring the embedding input text is on the nearer-term roadmap (in the entities collection), which is model-agnostic, and a way to implement the necessary prefix without a dedicated adapter 🌴

**Comment by brianpetro** [comment]
@aginiewicz I just checked the nomic v2 moe model on hugging face and I didn't see an onnx file which is required for the current local embeddings. 

If the model works via Ollama, then I do expect it the ollama embedding adapter to be ready before the end of june. If there is a compatible model (has .onnx in the files) then I could add the model to the current adapter pretty quickly and that would ship with the next release.

No specific citation expectations, but thanks for asking 🌴

**Comment by aginiewicz** [comment]
Great news! Seems that this model works with ollama since 0.7.0-RC1 (https://github.com/ollama/ollama/issues/9340#issuecomment-2880474426), before since 0.6.8 ollama was able to run it, but it gave unstable results.

**Comment by brianpetro** [comment]
@aginiewicz the latest update enables embeddings via Ollama. Let me know if it helps 😊🌴

**Comment by tophee** [comment]
I'm not sure if I'm doing anything wrong, but ot doesn't seem to work:

![Image](https://github.com/user-attachments/assets/73f56f75-3e3e-4c8d-94c4-cc97194e350e)

It does seem to iterate through all the chunks, but at a pace of 0 tokens/second, which I'm not sure how to interpret.

What I do see is that no smart links are shown. In addition, whenever I open a new (existing) note, it starts the whole embedding process again (or at least the above notification pops up again.

**Comment by tophee** [comment]
Cool! Now it works:

![Image](https://github.com/user-attachments/assets/b8a9fa8e-0171-4d02-b6a2-06ab1bb0ef5a)

Not quite as fast, but I think this is the better way 🙃

**Comment by brianpetro** [comment]
@tophee 
Are there any errors during the embedding process in the console logs? 🌴

**Comment by tophee** [comment]
There are no errors in the console just lots of these:

![Image](https://github.com/user-attachments/assets/a74f1978-284e-4616-9c43-4314b19458a8)

**Comment by brianpetro** [comment]
@tophee thanks for the screenshot. So it does appear the embeddings are saving (saves every ~100 embeddings). I'm testing out embedding a vault with the snowflake model to see if I can reproduce the issue 🌴

**Comment by tophee** [comment]
> Are you connecting to ollama over localhost?

yes

> Are you able to confirm whether any embeddings are being saved in your .smart-env/multi folder?

There are lots of .ajson files in that folder containing what looks very much like embeddings vectors. So, yes, the embeddings are being saved. Almost all of them have been created in the past few minutes, though (because I just restarted Obsidian. What's weird is that there are about 300 or so with "last modified" dates going back as far as 7 April (probably the day I tried embeddings for the first time) and as recently as last night (when I last ran the embeddings). 

My hunch is that somethings is going on there. It looks like the first reference to a model is always `..."embeddings":{"TaylorAI/bge-micro-v2":{...`, the next model that is mentioned seems to be something like `..."last_embed":{"hash":"46b91da3878ffc5216000ec07ef378cb1850fce9916a680d1a21a3c41262894b","tokens":457}},"nomic-ai/nomic-embed-text-v1.5":{"vec":...` (which is *not* the last model I used). The snowflake model (which is the ne I'm currently using) is mentioned in some but not all of those files. 

I cannot see any consistent pattern. For example, many (but not all) of the vector files that haven't been modified for some time, concern files that I have meanwhile excluded. So it makes sense why they would be updated (though I would have expected them to be deleted). 

But there are also old files that are not excluded and which do not contain a snowflake vector but they are not being updated.

On the other hand, the vast majority of all files seem to contain a snowflake vector, but they are still being modified (i.e. updated).

And they are indeed being updated (not recreated) becaus the creation date is old:

![Image](https://github.com/user-attachments/assets/6d4368dd-973d-43f7-879f-5d2ad38ea974)


> After switching models did you "reload sources"?

No.

**Comment by brianpetro** [comment]
Thanks for the details and screenshots. 

But still nothing is jumping out at me as the obvious issue 🤔

> though I would have expected them to be deleted

Smart Environment only loads the data files based on files it detects in the vault. So while those files aren't deleted automatically, there isn't a performance hit since they aren't accessed. The "Clean-up data" button in the settings should purge those files.

> Should I do "clear sources data"?

Yes, that's a good idea so we can rule out any corrupted data being the culprit 🌴

**Comment by tophee** [comment]
I did "clear sources data" (and confirmed that the entire multi-directory was gone), rebuilt the embeddings, aaaand ... same as before. The embeddings are rebuilt every time I restart Obsidian.

**Comment by brianpetro** [comment]
Are you able to confirm whether this happens for you in a test vault with only Smart Connections running?

If it does happen in the test vault, please share that test vault with me so I can better see what's happening.

If not, we might have to start exploring potential incompatibility issues with other plugins and sync methods 🌴

**Comment by brianpetro** [comment]
> I'm sorry, but I can't share the vault.

What if you create a new vault for testing purposes. It would only require a couple of test notes and only using Smart Connections plugin. This will help determine if it's a plugins issue or system level issue.

🌴

**Comment by brianpetro** [comment]
> Or are you saying that you can’t reproduce it with a standard vault and now we’re just confirming that I can’t either?

Correct.

For the sake of the project, I can't go deep into every edge case. If you can confirm the scope of the issue, in this case whether it's an OS issue or a third-party sync issue, then I can better triage this issue 🌴

**Comment by tophee** [comment]
OK, I tried a test vault (turns out, I already had one from earlier testing) and the issue is the same: when I restart obsidian, the emeddings are recreated:

![Image](https://github.com/user-attachments/assets/211dbf9e-93e4-4f13-9b2c-5e93acd39ceb)

Here is the vault:

[testvault.zip](https://github.com/user-attachments/files/20536579/testvault.zip)

**Comment by brianpetro** [comment]
@tophee thank you 😊

That is what I needed to make progress on this. Still not sure exactly what is happening, but I am now able to reproduce, so I should have a fix today.

Thanks again for your help and patience!

🌴

**Comment by brianpetro** [comment]
@tophee I believe the issue is now fixed in `v3.0.15`.

Thanks for your assistance and patience as I worked through this!

Let me know how it goes 😊🌴

**Comment by papatistos** [comment]
I was just going to write: Indeed, it works now! Well done and thank you so much.

But then I updated to 3.0.17 and then 3.0.18 which seems to have broken something. It keeps saying "No entity found" for whatever note I open. I can then refresh for that articuar note and it shows me relate notes (though only among very few selected notes, clearly not the entire vault) and I can't access the settings to refresh everything once more because it is stuck on:

![Image](https://github.com/user-attachments/assets/06f9aa83-ada5-487b-8e91-cc46a1b372a2)

Edit: Quick update on this: For reasons unrelated to this plugin or issue, I did an overhaul and restructuring of my vault and after that, the plugin went back to working fine. So this is currently no longer an issue for me. Let's hope it doesn't come up again/elsewhere. - So, once again: thanks for all the great work with the plugin and for getting it to work with ollama!

**Comment by brianpetro** [comment]
Glad to see it's working, thanks for the update 🌴

**Comment by papatistos** [comment]
Sorry to say that I was to fast to confirm. As I restart Obsidian, it now re-embeds *some of* the notes (every time):

![Image](https://github.com/user-attachments/assets/10d5f46f-4af1-44d5-84ef-2c17c725362a)

Something is still wrong. And as I try to access the settings to do a complete rebuild, I can't because I'm greeted by the same "Loading Obsidian Smart Environment...." as screenshotted above. (That is after the embeddings are done). So, I'm basically back to https://github.com/brianpetro/obsidian-smart-connections/issues/1024#issuecomment-2927970986

**Comment by brianpetro** [comment]
Are you able to update the test vault to reliably reproduce the issue? 🌴

**Comment by papatistos** [comment]
I think so, but I'm not entirely sure because there are several strange things happening and I'm not sure if some of them might be expected, such as that - in my main vault, I often have to either manually refresh the smart connections for an individual note or sometimes the plugin would embed a smaller number of notes/blocks (as if it realized: "oh, there is some new content, better update"). If that is intentional, I'm, not sure when exactly it is intentional. For example, some of the embeddings that were done at startup a couple of times, had different numbers of blocks (anything from 600 to several thousand), so if the plugin incrementally builds the embeddings as it discovers "new" notes, then that might explain why it "re-embedded" notes at startup: it might not have been re-embedding notes but just came to realize that it hadn't yet done all of them. It sounds a bit strange, though. But my point is: I cannot really reproduce this kind of UX in the text vault, as it would require me to actively work in the testvault, create new notes, etc.

What I can say, that right now, neither the main vault, nor the test-vault are doing any embeddings at startup, but I'm not sure if this behaviour is gone for good or whether it will come back, seemingly out of nowhere, like it did yesterday.

One thing that I consistently see in both the main and the text vault is this when I try to access the settings:

![Image](https://github.com/user-attachments/assets/e81c8ccb-cbc5-4c92-a068-4613559a9bde)

But I realized that I can also access the smart environment settings via the smart chat settings:

![Image](https://github.com/user-attachments/assets/1372cec5-e743-4781-b93f-3544db558753)

But also here, I'm not sure what parts of this behavious might be intentional, e.g. is it normal that a single plugin registers as two different plugins in the Obsidian Settings? 

I noticed that v.3.0.19 is out now. What I'm saying above refers to v 3.0.18

**Comment by brianpetro** [comment]
@tophee thanks for the update.

The Smart Connections settings bug (persistent "Loading Obsidian Smart Environment") has been fixed in the latest patch.

Smart Chat is developed as a standalone Obsidian plugin, so the settings are in a different tab. While the new Smart Chat was originally slated to be released separately, community members in our bi-weekly [Lean Coffee meetings](https://lu.ma/calendar/cal-ZJtdnzAdURyouM7) convinced me to keep them together, for now.

In a recent patch version, I fixed a bug in the `should_embed` logic. While I'm not certain it was the cause of what you experienced, it is definitely a possibility (the bug was identified due to undersized blocks being embedded).

If you do manage to clearly identify any issues, reproducing them in the test vault will be the quickest way to help me resolve them.

Thanks for the help 🌴
